In [1]:
import pandas as pd
import numpy as np

# Create new time series data (e.g., February 2023)
data = {
    'date': pd.date_range(start='2025-02-01', periods=10, freq='D'),
    'value': [12, 18, 21, 17, 25, 29, 33, 28, 24, 20]
}
df = pd.DataFrame(data)

df

        date  value
0 2025-02-01     12
1 2025-02-02     18
2 2025-02-03     21
3 2025-02-04     17
4 2025-02-05     25
5 2025-02-06     29
6 2025-02-07     33
7 2025-02-08     28
8 2025-02-09     24
9 2025-02-10     20

In [2]:
# Set the date column as the index
df.set_index('date', inplace=True)
df

            value
date
2025-02-01     12
2025-02-02     18
2025-02-03     21
2025-02-04     17
2025-02-05     25
2025-02-06     29
2025-02-07     33
2025-02-08     28
2025-02-09     24
2025-02-10     20

In [3]:

# Calculate the moving average with a window size of 4

df['rolling_mean_4'] = df['value'].rolling(window=4).mean()
df

            value  rolling_mean_4
date
2025-02-01     12             NaN
2025-02-02     18             NaN
2025-02-03     21             NaN
2025-02-04     17           17.00
2025-02-05     25           20.25
2025-02-06     29           23.00
2025-02-07     33           26.00
2025-02-08     28           28.75
2025-02-09     24           28.50
2025-02-10     20           26.25

In [4]:
# use the above time series data sample
df['rolling_std_4'] = df['value'].rolling(window=4).std()

print(df)

            value  rolling_mean_4  rolling_std_4
date
2025-02-01     12             NaN            NaN
2025-02-02     18             NaN            NaN
2025-02-03     21             NaN            NaN
2025-02-04     17           17.00       3.741657
2025-02-05     25           20.25       3.593976
2025-02-06     29           23.00       5.163978
2025-02-07     33           26.00       6.831301
2025-02-08     28           28.75       3.304038
2025-02-09     24           28.50       3.696846
2025-02-10     20           26.25       5.560276

In [5]:
df['rolling_expanding_mean'] = df['value'].expanding().mean()
df

            value  rolling_mean_4  rolling_std_4  rolling_expanding_mean
date
2025-02-01     12             NaN            NaN               12.000000
2025-02-02     18             NaN            NaN               15.000000
2025-02-03     21             NaN            NaN               17.000000
2025-02-04     17           17.00       3.741657               17.000000
2025-02-05     25           20.25       3.593976               18.600000
2025-02-06     29           23.00       5.163978               20.333333
2025-02-07     33           26.00       6.831301               22.142857
2025-02-08     28           28.75       3.304038               22.875000
2025-02-09     24           28.50       3.696846               23.000000
2025-02-10     20           26.25       5.560276               22.700000

In [6]:
df['running_total'] = df['value'].expanding().sum()
df

,value,rolling_mean_4,rolling_std_4,rolling_expanding_mean,running_total
date,,,,,
2025-02-01,12,NaN,NaN,12.000000,12.0
2025-02-02,18,NaN,NaN,15.000000,30.0
2025-02-03,21,NaN,NaN,17.000000,51.0
2025-02-04,17,17.00,3.741657,17.000000,68.0
2025-02-05,25,20.25,3.593976,18.600000,93.0
2025-02-06,29,23.00,5.163978,20.333333,122.0
2025-02-07,33,26.00,6.831301,22.142857,155.0
2025-02-08,28,28.75,3.304038,22.875000,183.0
2025-02-09,24,28.50,3.696846,23.000000,207.0
2025-02-10,20,26.25,5.560276,22.700000,227.0